// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqzmftlavzywjxtifcym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xem1mdGxhdnp5d2p4dGlmY3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzE0MjUsImV4cCI6MjA2NjUwNzQyNX0.HdvLSIb18c_ILOXg7AQqb_yqbHt7hhYBSisio1cTjNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);